<<<<<<< HEAD
# Main Stuff
title: Competition
url: competition.streamdata.io

# Partners
philosophy: This is the Streamdata.io competition dashboard. We are actively looing to keep n eye on the competition in the event-driven API space.

partners:
  - name: Xignite
    ranking: 1
    description: Xignite inspire the future of finance by making market data easy.
    url: http://www.xignite.com/
    image: https://i1.wp.com/streamdata.io/wp-content/uploads/2018/01/xignite-1.png?fit=150%2C39&ssl=1
    latest:
      - title: Xignite, A Leader In Market Data Streaming API
        url: https://streamdata.io/blog/xignite-market-data-streaming-api-leader/
      - title: Postman Collections For Each Xignite Global Currencies API
        url: https://streamdata.io/blog/postman-collections-xignite-currencies-api/

# Other Settings
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

github_user: streamdata-projects
github_repo: partners
github_branch: master
=======
>>>>>>> 2fef17d6af13109751543af657ad070b27f7c0a3
